### PR TITLE
Use Responsive Font Sizes

### PR DESCRIPTION
**Pull request by vanillajonathan**
Change headers to use Responsive Font Sizes (RFS) from Bootstrap.

### CODE REVIEW

**Comment by Ionaru** [comment]
Why is this needed? The editor already scales its text and icons with font sizes.

**Comment by vanillajonathan** [comment]
The Bootstrap documentation has more information:
> The mechanism automatically calculates the appropriate values based on the dimensions of the browser viewport.

https://getbootstrap.com/docs/5.2/getting-started/rfs/

The headers are defined to have the same font-size as Bootstrap which makes it play nice with websites using Bootstrap.

**Comment by Ionaru** [comment]
Can you explain what is different with RFS vs without it? How it affects the editor in different conditions and the benefits of it?

**Comment by vanillajonathan** [comment]
The advantages listed in the README for RFS is:

> - No need to rescale paddings or margins anymore.
> - Text won't be chopped off in smaller viewports when RFS is applied to font sizes.
> - RFS will prevent the font size from rescaling too small, so readability can be assured.
> - The font sizes of all text elements will always remain in relation with each other.

https://github.com/twbs/rfs

The README also includes a animated GIF.

But my personal motivation is just to have the header sizes be consistent with Bootstrap since that is what I use.

**Comment by Ionaru** [comment]
How does it affect the editor? What noticeable differences will there be for users before and after the change?

**Comment by vanillajonathan** [comment]
It doesn't affect the editor, the sizes of the headers will be slightly different, but users are not likely to notice.

Before (now):
headers-before

After:
headers-after

**Pull request merged**
