### PR TITLE
improve preview update performance

### PR DESCRIPTION
**Pull request by axe312ger**
I ported https://github.com/sparksuite/simplemde-markdown-editor/pull/634 to easymde.

Previews are now way more performant and less flickery :)

### CODE REVIEW

**Comment by axe312ger** [comment]
Dang my prettier plugin auto-formatted the code, the changes are way less crazy as it seems. Will remove the reformatting later

**Comment by axe312ger** [comment]
Reduced to diff to include only actual changes.

Demo: https://axe312ger.github.io/mdx-live-editor/

**Comment by Ionaru** [comment]
A few things I've noticed with this change:

* html2idom for some reason has very low download rates, why? If this feature is so prevalent in other editors, what do they use?

* Some changes to the markdown still cause the preview to reload. For example changing a header to normal text or vise-versa, or removing a few lines above an iframe. While making text bold does not reload it. This is inconsistent behavior, why do those markdown changes cause a reload while others do not?

**Comment by axe312ger** [comment]
@lonaru you are right here, I just ported the old PR. I came accross https://github.com/developit/htm which is low footprint, well maintained and the performance is blazing.

I cant find any more flickering, even when using complex content elements.

**Comment by axe312ger** [comment]
I published this branch as `npm i @axe312/easymde@beta` is anybody wants to play around.

My https://github.com/axe312ger/mdx-live-editor is using this for now, you can use it as demo for this branch :)

**Comment by axe312ger** [comment]
Ohh, sorry for not testing the default usecase.

Looks like the way easyMDE handles the preview rendering won't be enough for my mdx editor. I might build my own editor based on codemirror or ace.

Should we keep this PR open? I think I have no use for it anymore, maybe somebody wants to chime in?

Best

**Pull request closed without merging**
