### PR TITLE
Modernize theme

### PR DESCRIPTION
**Pull request by vanillajonathan**
Visual refresh of the theme to modernize it.

### CODE REVIEW

**Comment by vanillajonathan** [comment]
@Ionaru Change the border color from `#bbb` and `#ddd` to `#ced4da` so that it matched Bootstrap.

**Comment by Ionaru** [comment]
"Modern" is subjective, I don't think we should touch the theme until #447.

**Comment by vanillajonathan** [comment]
Yes, it is subjective. This modification does away with the borders and use a more flat style. Try it and see if you like it.

Might be something for the new editor.

For the current version might want to consider just changing the border color though, because now it doesn't match with the border color of the `form-control` class in Bootstrap, also it uses two different colors for borders, it uses both `#bbb` and `#ddd` resulting in the border of the toolbar being darker than other border of the editor which seems rather odd and might not be the intended look.

**Comment by Ionaru** [comment]
The editor was never made to integrate perfectly with Bootstrap. The design is purposefully minimal and can be easily edited by website creators to match their website theme. I don't think it's a good idea to copy over all the colours that bootstrap (currently) uses.

**Comment by vanillajonathan** [comment]
Then consider at least being consistent in the border color that is used, because now EasyMDE uses two different border colors, both `#bbb` and `#ddd` so it looks inconsistent and off. It looks like a "design bug" that was never intended.

**Comment by Ionaru** [comment]
I agree it's good to be consistent. I'll leave the choice between `#bbb` and `#ddd` up to you.

**Comment by vanillajonathan** [comment]
I would prefer `#ced4da` as that is what is used in Bootstrap. Else `#ccc` would be between `#bbb` and `#ddd` and closer to Bootstrap's `#ced4da` color.

But this PR was to modernize the theme and also includes other changes such as flat border-less buttons with more rounded corners. So this PR can be for EasyMDE v3.

**Pull request closed without merging**
