### PR TITLE
Refactor into using a map for icon classes

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by vanillajonathan** [comment]
@Ionaru Please merge!

**Comment by Ionaru** [comment]
Firstly, this is a project I maintain in my free time next to my day job. I look at all the issues and PRs, some take longer to look through and make a decision for. Please allow me the time for that.

Secondly, I'm not seeing the use of this change. Sure it makes a neat little variable containing all icons, but ends up being more code for the exact same effect. I rather like the current look of the `toolbarBuiltInButtons` variable as it shows how users can add their own custom buttons.

**Comment by vanillajonathan** [comment]
This PR serves as the underlying foundation for the next step.

Which is:
```javascript
options.iconClassMap = extend({}, iconClassMap, options.iconClassMap || {});
```

Which allows integrators to easily use other icon sets without having to recreate every button themselves.

**Comment by Ionaru** [comment]
Then build what you want to build and provide the completed thing as a PR. Smaller increments through PRs only increase the risk of half finished functionality ending up in the source code.

**Comment by vanillajonathan** [comment]
Can this be merged?

**Comment by Ionaru** [comment]
I would prefer the `iconClassMap` to use the `name` property of the toolbar buttons because that is what the `toolbar` option uses as well.

**Comment by vanillajonathan** [comment]
Alright, done.

**Comment by willGabrielPereira** [comment]
Hi @Ionaru, this PR was made for exactly what? because it keeps doing the same effect, you can't change the icons even after this changes.

The https://github.com/Ionaru/easy-markdown-editor/pull/501 looks like really fix this. Please take a look in it!

**Comment by vanillajonathan** [comment]
@willGabrielPereira This PR was never meant to let you change the icons, it was just a refactor and a stepping stone to later expose it as options. See the comment https://github.com/Ionaru/easy-markdown-editor/pull/454#issuecomment-1133860132 above.

**Pull request merged**
