### PR TITLE
Added example directory with default demo file

### PR DESCRIPTION
**Pull request by jecsham**
I added a `example/index.html` with the easymd editor loaded from `/dist` directory,
Now developers can use the `example/index.html` file as a playground.

### CODE REVIEW

**Comment by A-312** [comment]
@Ionaru This PR seems ready

**Comment by A-312** [comment]
@Ionaru Does this PR need more change to be merged ?

**Comment by Ionaru** [comment]
I'm not convinced this is needed, can you give some arguments or reasons why the documentation or demo website isn't adequate, if possible I would like to improve those instead of introducing this file.

**Comment by jecsham** [comment]
Just to expriment quicly with your own code, configs, etc.

**Comment by A-312** [comment]
Very useful to test change on this repository

**Pull request merged**
