### PR TITLE
Added multilanguage translation

### PR DESCRIPTION
**Pull request by dima-bzz**
Added multilanguage translation. Added cursorActivity for position cursor.

### CODE REVIEW

**Comment by Ionaru** [comment]
While I appreciate your contribution to the project and I like multilanguage support a lot, I don't think it should be the responsibility of this editor to keep translations in its source code.

The editor is highly configurable, and when #171 is merged I think all the options are present for developers to provide their own translations.

**Comment by dima-bzz** [comment]
@Ionaru Ok, can then make one localization variable and register the default translation in it?

**Comment by Ionaru** [comment]
I would rather not introduce any big configuration changes because that would mean existing applications will break when updating.

I think the options are okay as they are now.

**Comment by dima-bzz** [comment]
@Ionaru I meant to make one variable:

```
var locale = {
"promptTexts": {
            "link": "URL for the link:",
            "image": "URL of the image:"
        },
        "status": {
            "lines": "lines:",
            "words": "words:",
            "autosave": "Autosaved:"
        },
        "errorMessages": {
            "noFileGiven": "You must select a file.",
            "typeNotAllowed": "This image type is not allowed.",
            "fileTooLarge": "Image # image_name # is too big (#image_size #). \ nMaximum file size is # image_max_size #.",
            "importError": "Something went wrong when uploading the image # image_name #."
        },
        "imageTexts": {
            "sbInit": "Attach files by drag and dropping or pasting from clipboard.",
            "sbOnDragEnter": "Drop image to upload it.",
            "sbOnDrop": "Uploading image #images_names # ...",
            "sbProgress": "Uploading # file_name #: # progress #%",
            "sbOnUploaded": "Uploaded # image_name #",
            "sizeUnits": "b, Kb, Mb"
        },
        "toolbar": {
            "bold": {"title": "Bold"},
            "italic": {"title": "Italic"},
            "strikethrough": {"title": "Strikethrough"},
            "heading": {"title": "Heading"},
            "heading-smaller": {"title": "Smaller Heading"},
            "heading-bigger": {"title": "Bigger Heading"},
            "heading-1": {"title": "Big Heading"},
            "heading-2": {"title": "Medium Heading"},
            "heading-3": {"title": "Small Heading"},
            "code": {"title": "Code"},
            "quote": {"title": "Quote"},
            "unordered-list": {"title": "Generic List"},
            "ordered-list": {"title": "Numbered List"},
            "clean-block": {"title": "Clean block"},
            "link": {"title": "Create Link"},
            "image": {"title": "Insert Image"},
            "upload-image": {"title": "Import an image"},
            "table": {"title": "Insert Table"},
            "horizontal-rule": {"title": "Insert Horizontal Line"},
            "preview": {"title": "Toggle Preview"},
            "side-by-side": {"title": "Toggle Side by Side"},
            "fullscreen": {"title": "Toggle Fullscreen"},
            "guide": {"title": "Markdown Guide"},
            "undo": {"title": "Undo"},
            "redo": {"title": "Redo"}
        }
};
```
and already the developer himself will set the localization.

```
var easyMDE = new EasyMDE({
localization: {
        "promptTexts": {
            "link": "URL:",
            "image": "URL :"
        },
...
}
})
```

**Comment by Ionaru** [comment]
Can we somehow wrap this into a something that will not cause a breaking change?

**Comment by A-312** [comment]
Something like : `Object.assign(editor.options, local.xx)` should be great

**Comment by dima-bzz** [comment]
Add a single variable with translation or localization file?

**Comment by Ionaru** [comment]
Again, this would be a breaking change because we would be **removing** options that currently exist. (https://semver.org/#spec-item-8)
At this time I do not want any breaking changes to the editor and only provide backwards-compatible changes because of all the extra work that a new major version brings like making a migration guide and providing support for the older version in case of security issues etc.

**Comment by dima-bzz** [comment]
This option is not suitable ?

**Comment by A-312** [comment]
Don't close 😢 

> This option is not suitable ?

You have to cancel your change which remove actual setting or did something like that:

```
`label.test = old.option || new.option;
```

To keep support with old version

**Comment by dima-bzz** [comment]
@A-312 I added a new PR which adds translation for toolbar

**Pull request closed without merging**
