### PR TITLE
Added time format and text for autosave

### PR DESCRIPTION
**Pull request by dima-bzz**

### CODE REVIEW

**Comment by A-312** [comment]
US date format is not the only one. Some country do : dd/mm/yyyy 

Can you use `.toLocaleString()` ? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

**Comment by dima-bzz** [comment]
But here we are talking about the time, not the date.

**Comment by A-312** [comment]
> But here we are talking about the time, not the date. You use a date?

I understand 24th Decembre: 😖 

> Added option time format for autosave (12/24)

It is maybe better to write:

Time format AM/PM or 24h. Defaults to AM/PM.

**Comment by dima-bzz** [comment]
@A-312 Added DateTimeFormat

**Pull request merged**
