### PR TITLE
Add keyboard shortcuts for headings

### PR DESCRIPTION
**Pull request by vanillajonathan**
These are the same keyboard shortcuts used in TinyMCE.

### CODE REVIEW

**Comment by Ionaru** [comment]
I'm not convinced <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd> is the right shortcut for this function. I would prefer it to be more in line with the existing shortcuts.

Maybe <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd>? That shortcut is also used in Microsoft Word for and probably is more in line with what people would expect.

**Comment by vanillajonathan** [comment]
The reason I used <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd> is because that is what TinyMCE uses.

I can change it to <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd> if  you would like me to (or you could do it yourself).

**Comment by vanillajonathan** [comment]
What do you think?

**Comment by Ionaru** [comment]
Change it to <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd> and add it to the README as well, please.

**Pull request merged**
