### PR TITLE
Add support for text buttons

### PR DESCRIPTION
**Pull request by vanillajonathan**
This adds support for text in buttons and in dropdown menu.

### CODE REVIEW

**Comment by Ionaru** [comment]
I don't see why anyone would want this, none of the styling works with text...

image

**Comment by vanillajonathan** [comment]
With this CSS tweak it looks better.

**Review by Ionaru — CHANGES_REQUESTED** [review]
Still needs some work.

Maybe some extra padding around text so they look like the icon buttons.
image

I personally think bold text look better but this might depend on the icon set someone is using. Maybe you can wrap the text in an element so it can be styled by developers. Standard bold text `font-weight: bold` looks pretty good with the default icons in my opinion.
image

Longer names with separate works don't work well in dropdown menus.
image

Longer names with long words make the dropdown display horizontally.
image

**Review by Ionaru — CHANGES_REQUESTED** [review]
An empty `<i>`  element is created when a button is used with just text.

image

---

I think there should be some spacing left and right of the text. When combined with an icon (like you show in the README) does not look good.

image

---

What about this?

> I personally think bold text look better but this might depend on the icon set someone is using. Maybe you can wrap the text in an element so it can be styled by developers. Standard bold text `font-weight: bold` looks pretty good with the default icons in my opinion.
image

**Review by Ionaru — APPROVED** [review]

**Pull request merged**
