### PR TITLE
Upload images functionality update

### PR DESCRIPTION
**Pull request by JeroenvO**
Thanks to @roipoussiere for starting on this functionality!
Because https://github.com/Ionaru/easy-markdown-editor/pull/71 was very quiet, i made an updated version.
- Merge EasyMDE version 2.7.0 with https://github.com/Ionaru/easy-markdown-editor/pull/71 
- replace MouseEvent(click) with .click() for IE11 compatibility (used together with polyfill.io for ES6 )
- Fix status bar update when dragging but not dropping
- Fix progress showing on statusbar
- Add option for CSRF token to include in AJAX call for imageupload (for instance used with Django)
- Fix status bar show upload error and reset after upload error
- Add option for server side error messages on image upload.

I did not change the use of lots of top-level API keys, as the discussion on how to implement this is still ongoing. I would suggest to change the API in the V3 milestone instead of with these PRs.

### CODE REVIEW

**Comment by Ionaru** [comment]
My changes:

* Merged master into upload_images to bring branch up-to-date.
* Small edit in the code that adds `upload-image` to the status bar array.
* Edited changelog.
* Auto-formatted the code.

**Comment by JeroenvO** [comment]
Looks good!

**Comment by LinusU** [comment]
@Ionaru, @JeroenvO I'm a bit late to this now, just saw it since it closed #46 now.

> **imageUploadEndpoint**: The endpoint where the images data will be sent, via an asynchronous *POST* request. The server is supposed to save this image, and return a json response.

I would strongly urge you to re-design this part. This places restrictions on how to design the server API in a front-end library. It makes it hard to use with any existing file uploading API.

My recommendation is to have the user supply a function that saves the image, and returns a promise of the markdown that it wants to insert. That way the uploading can be customised by the end user.

I actually brought this up in the initial issue:

> [...] I would love it if there was some way to register hooks for when a file is dropped onto the editor.
>
> To be clear, I would not like the editor to do anything regarding the actual uploading of the files. Just a hook that calls my own function when a file has been dropped.
>
> My own code could then upload the file, and insert the correct markdown syntax for it to be displayed

The way this is designed now, I won't be able to use it unless I redesign my backend API to have one special route that won't follow the conventions of the other endpoints.

I also can't use it because I want to insert the image dimensions in the markdown output to support retina images.

I would absolutely love it if you could instead expose a hook for when a file was dropped, and way to asynchrounsly return the markdown that I want to be inserted at the point the file was dropped at.

Together with this I think you should also drop `imageMaxSize` since that could be easily checked in the supplied function...

**Comment by Ionaru** [comment]
@LinusU I've made a new PR, let me know if that is more useful to you. (#104)

**Comment by StarWar** [comment]
@Ionaru there should be an option to return fileURL from the server in case of media hosted on s3, i.e. different subdomain, we might need to add whole URL not just filepath.

**Pull request merged**
